### ISSUE TITLE
how to disable sourcemap?

### ISSUE THREAD

**Issue by fedeoo** [gdborton/webpack-parallel-uglify-plugin#14]

**Comment by gdborton** [comment]
Sourcemaps should be respecting the `devtool` option in your webpack config. Are you seeing otherwise?

**Comment by fedeoo** [comment]
@gdborton  it works. but I won't change devtool because I want to keep scss sourcemap.

**Comment by derekdon** [comment]
@gdborton It's fairly standard not to set devtool if you're using the SourceMapDevToolPlugin directly.

**Comment by gdborton** [comment]
I'll be honest, I had no idea that plugin even existed. I'll take another look at the interop and see about updating this plugin.

**Comment by derekdon** [comment]
@gdborton Yeah basically your devtool string is converted into an instance of it or the eval version under the hood. See https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L212. When you need more control you can just use it directly and omit the devtool setting.

**Comment by gdborton** [comment]
@fedeoo @derekdon This has been fixed in the 1.0.0 release. Source maps are now controlled via the `sourceMap` boolean in the plugin's options.

I'll leave this issue open for a little while longer to address any remaining issues you may have.
