### ISSUE TITLE
Possible hang up problem

### ISSUE THREAD

**Issue by hustcer** [gdborton/webpack-parallel-uglify-plugin#19]
Thanks for the great work, It really speed up my static assets building process. However, it's strange that it could cause the system hang up in some rare cases.
I still can't find any clue, It's hard to recurrence the case, I'm sorry.
Did anyone meet the same issue?

**Comment by hustcer** [comment]
```
node@v7.7.1
centos-release-6-3.el6.centos.9.x86_64
Linux iZbp16onact3nfhyzuw9e7Z 2.6.32-358.6.2.el6.x86_64 #1 SMP Thu May 16 20:59:36 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
Hypervisor vendor:     KVM

free -m
             total       used       free     shared    buffers     cached
Mem:          7872       7685        187          0        292       1795
-/+ buffers/cache:       5596       2275
Swap:            0          0          0

```

**Comment by gdborton** [comment]
@hustcer I'm not sure you mean when you say that your system hangs up.  I can imagine one of two scenarios, either running out of memory or you've got a lot of processes running and your CPU is being spent in task switching. 

You might want to try updating to a newer version, there have been a few changes in the architecture that might alleviate your problem.

If that doesn't work, you can try lowering the number of workers used (defaults to CPUs - 1) and see if that helps.  Even without parallelization the built in caching layer is super fast.

**Comment by hustcer** [comment]
@gdborton Thanks for your suggestion, it helps.
