### ISSUE TITLE
workers.setMaxListeners exceeds hardcoded value

### ISSUE THREAD

**Issue by sboulos** [gdborton/webpack-parallel-uglify-plugin#20]
In our project, we get this warning:

(node:19903) Warning: Possible EventEmitter memory leak detected. 101 message listeners added. Use emitter.setMaxListeners() to increase limit

It appears in uglifier.js, the worker is hardcoded to 100 max listeners:
worker.setMaxListeners(100);

I will open a pull request to make that number a config option.

**Comment by gdborton** [comment]
@sboulos I just merged a PR that will fix this without requiring a worker count to be provided. I've got another change in the pipeline. Once that is merged, I'll be cutting a new release.

**Comment by gdborton** [comment]
@sboulos This is fixed in 0.4.2.
