### ISSUE TITLE
Add ability to use uglify-es (ES2015 support) as a minifier

### ISSUE THREAD

**Issue by stevewillard** [gdborton/webpack-parallel-uglify-plugin#22]
Recently support for ES2015 was release with Uglify:
https://www.npmjs.com/package/uglify-es

It might be a fun idea to try to switch on this parser with a flag in the plugin.

**Comment by gdborton** [comment]
This is coming soonish.

**Comment by scott-thrillist** [comment]
+1 doing some ES6 build testing as our IE11 marketshare is inching closer to >1% and this great plugin is the last piece blocking me :)

**Comment by gdborton** [comment]
@stevewillard @scott-thrillist I've updated the plugin to include support for `uglify-es`, you can specify that you want to use uglify-es by providing `uglifyES: { ...uglifyOptions }`. The newest release (1.0.0) also updates uglifyJS to use uglify-js@3, so be aware of that if you have any options that differ in 2 vs 3.
