### ISSUE TITLE
Merge with the official contrib plugin?

### ISSUE THREAD

**Issue by mikesherov** [gdborton/webpack-parallel-uglify-plugin#32]
great work on this plugin. Have you given any thought to merging with the official webpack-contrib uglify plugin?

That way, every Webpack user can receive this massive speedup without having to find this plugin! Also, it doesn't always make sense to parallelize, so by moving into the official plugin, we can intelligently choose whether to parallelize or not, and give users an option to parallelize or not.

Thoughts?

**Comment by hulkish** [comment]
Great work here.. Would need to upgrade to `uglify-es` to merge with `uglifyjs-webpack-plugin`. tho

**Comment by mikesherov** [comment]
@hulkish did you notice https://github.com/gdborton/webpack-parallel-uglify-plugin/pull/31

**Comment by hulkish** [comment]
ah, very cool then

**Comment by gdborton** [comment]
@mikesherov I haven't really given it any thought... do you think they'd be open to pulling it in?  

Also, users can disable parallelization by specifying their worker count, and we only spawn workers at `Min(CPUs - 1, # of files to be minimized - # of files that are cached)`, so we might spawn no workers if everything is cached. There isn't yet a way to run in band without spawning a worker.

**Comment by d3viant0ne** [comment]
@gdborton - Quick introduction, I'm the lead for `webpack-contrib`, Webpacks loader & plugin ecosystem.

So, right out of the gate there is one issue. We can't `transfer in` an ISC licensed repo ( legal issues ).

We could, assuming you are interested merge the two ( so to speak ) & add you as a maintainer to uglifyjs-webpack-plugin. 

I'm personally on the fence here. I think multiple options for any given thing drives innovation though there is also value to the community to focus development efforts and in this particular case, I think the latter would have the most benefit to the community.

If you are interested or would just like to discuss it further, shoot me a DM on Twitter ( same name ) with an email you would like to use for Slack & I will get you an invite.

**Comment by dfguo** [comment]
Really hope this will be a part of official plugin. We see great perf gain after using it. I hope more people can get the speed gain.

**Comment by gdborton** [comment]
@d3viant0ne I'm totally fine with updating the license to MIT. I'm on the fence about replacing the current Uglify plugin (I recognize that I'm not the best maintainer), but am certainly open to talking about it.

**Comment by d3viant0ne** [comment]
@gdborton - My DMs are open on Twitter ( same handle ). Shoot me an email & i'll get you into the Webpack slack & we can chat about all of this.

**Comment by gdborton** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin has been updated to include parallelization and caching, so I don't think it makes sense to merge these anymore.
