### ISSUE TITLE
The plugin is not fast enough.

### ISSUE THREAD

**Issue by lcxfs1991** [gdborton/webpack-parallel-uglify-plugin#36]
I compared [webpack-uglify-parallel](https://github.com/tradingview/webpack-uglify-parallel) and webpack-parallel-uglify-plugin and find that webpack-parallel-uglify-plugin is slower. Do you have plans to make it faster?

**Comment by gdborton** [comment]
How big of a difference are you noticing?  This plugin defaults to cpus - 1, while that one recommends cpus, so that might account for the speed difference. Also, this plugin has a builtin caching layer that provides incredibly fast rebuilds.
