### ISSUE TITLE
Plugin doesn't work with webpack v3.

### ISSUE THREAD

**Issue by lin-hun** [gdborton/webpack-parallel-uglify-plugin#39]
Desc as title.
I find that it so fast means not working correctly.
![image](https://user-images.githubusercontent.com/7136386/30012840-696fa816-9175-11e7-87a1-75d54a6ed074.png)

**Comment by zhenyong** [comment]
@lin-hun 

Official uglifyjs plugin, which now supports parallelization [webpack-contrib/uglifyjs-webpack-plugin: UglifyJS plugin for webpack](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/#options)

**Comment by gdborton** [comment]
You shouldn't have any problems with webpack 3... are you getting any errors?

**Comment by lin-hun** [comment]
ok, I mean it not make any err & not uglify my code

**Comment by gdborton** [comment]
@lin-hun Could you create a repository that recreates this problem? We use this daily at Airbnb and haven't had any issues with it.
