### ISSUE TITLE
React dead code elimination error in production

### ISSUE THREAD

**Issue by lifeng1893** [gdborton/webpack-parallel-uglify-plugin#43]
there is problem when I use `webpack-parallel-uglify-plugin`, but it's OK using `uglifyjs-webpack-plugin`. I'm not sure it is caused by this plugin.
the problem show as below:
`Uncaught Error: React is running in production mode, but dead code elimination has not been applied. Read how to correctly configure React for production: https://fb.me/react-perf-use-the-production-build at <anonymous>:21:35`

**Comment by gdborton** [comment]
@lifeng1893 Could you create an example repo that produces this issue? We've been using this plugin at Airbnb since its creation and haven't experienced this issue.

**Comment by lifeng1893** [comment]
@gdborton ummm..I tried again, it's OK now, maybe the error caused by any other reason.
