### ISSUE TITLE
Problem with file-loader

### ISSUE THREAD

**Issue by remko** [gdborton/webpack-parallel-uglify-plugin#44]
I have a JS file with the following code:

       import 'file-loader!./foo.js';

This gives the following error:

        ERROR in minifying d41d8cd98f00b204e9800998ecf8427e.js
        S.input is not a function

where `d41d8cd98f00b204e9800998ecf8427e.js` corresponds to `foo.js`.

Is there a way to work around this problem (except excluding based on filename, since I can't predict the filename).

**Comment by gdborton** [comment]
I'm guessing this is loading the `foo.js` file directly, are the contents valid js?
