### ISSUE TITLE
How does this compare to uglifyjs-webpack-plugin?

### ISSUE THREAD

**Issue by mnpenner** [gdborton/webpack-parallel-uglify-plugin#46]
[`uglifyjs-webpack-plugin`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) now supports a `parallel` option. Does that make these two plugins more-or-less the same, or is one faster than the other?

**Comment by gdborton** [comment]
I haven't run any bench marks against the built in plugin, but a few people have reported that it's minimally faster. Either should be "fast enough™".

That being said it automatically places you onto uglify-es, which is in a semi-unmaintained state AFAIK - https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/262

Ignoring that, this plugin allows for either UglifyJS or UglifyES depending on the options that you provide. At Airbnb, we're relying on this behavior to prevent unintentionally shipping es6 code that sometimes sneaks into our node_modules/, as UglifyJS will fail to parse.
