### ISSUE TITLE
source map not working

### ISSUE THREAD

**Issue by Yangqin0607** [gdborton/webpack-parallel-uglify-plugin#52]
I have used webpack-parallel-uglify-plugin. It does generate *.js.map, and the source files also contains comments like "sourceMappingURL=a-614d71f532b520f2be01.js.map". But when I open the page in browsers, it was empty.  Here are my config file and the picture in browser.
webpack: 3.11.0
webpack-parallel-uglify-plugin: 1.1.0
```
devtool='source-map';
plugins.push(
    new ParallelUglifyPlugin({
       sourceMap: true,
       uglifyJS: {
          mangle: {},
          compress: {
            warnings: false,
            properties: false,
          },
          output: { comments: false },
        },
    })
);
```
<img width="457" alt="issue" src="https://user-images.githubusercontent.com/17544463/41150093-c6d6a6ea-6b3f-11e8-9e87-aa663932568f.png">

If I use webpack.optimize.UglifyJsPlugin, every thing works fine.
```
 plugins.push(new webpack.optimize.UglifyJsPlugin({
          sourceMap: true,
          mangle: {},
          compress: {
            warnings: false,
            properties: false,
          },
          output: {},
          comments: false,
        }));
```
Could you please tell me what's wrong with my config file? Thank you so much!

**Comment by Rainsho** [comment]
me too ...

**Comment by Rainsho** [comment]
It seems that `uglifyJS` works fine to me.

**Comment by Rainsho** [comment]
Not yet, since the code delivered to the plugin had already transformed by `babel`,  for now we use `uglifyJS` to minify the code.

**Comment by xiaoTuiMao** [comment]
anyone solve this problem?

**Comment by gdborton** [comment]
@Yangqin0607  I'm going to be creating and linking to a sample project showing a simple config and demo w/ sourcemaps working. Closing this out for now, but if you're still having trouble please reopen and I'll try to help you out.
