### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by brainee** [gdborton/webpack-parallel-uglify-plugin#53]
when i use webpack-parallel-uglify-plugin instead of UglifyJsPlugin,ti raise up an error,but use UglifyJsPlugin the project is running success,the error is :07.js:formatted:5238 Uncaught TypeError: Cannot call a class as a function,my config is simple,pluginArr.push(new ParallelUglifyPlugin({
                cacheDir: '.cache/',
                uglifyJS:{
                    compress: {
                        warnings: true,
                    }
                }
            })
            );

**Comment by gdborton** [comment]
@brainee Given the age of this issue, I expect that you were able to address the problem yourself or have updated to the plugin maintained by the webpack team.  I'm going to close this, but if you still need help feel free to reopen and I'll try to help get you sorted out.
