### ISSUE TITLE
Whether this configuration is supported：safari10

### ISSUE THREAD

**Issue by sw811** [gdborton/webpack-parallel-uglify-plugin#57]
new UglifyJsPlugin({
                            uglifyOptions: {
                                safari10: true
                            }
                        })

**Comment by gdborton** [comment]
@sw811 This package is basically a straight pass through to uglifyJS, it should support all browsers depending on your configuration. It's been a while since I've looked at this, so I'm not familiar with the exact config that you're looking for.
