### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by wxy1995** [gdborton/webpack-parallel-uglify-plugin#58]
Hi,

  I got the following warning message when building my project:
```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

After checking out  webpack dependencies (webpack, loaders, plugins, …), i found out that `webpack-parallel-uglify-plugin` uses `compiler.plugin('xxx')`.

Now that webpack 4 is using a new plugin system and deprecates the previous APIs, should we update webpack-parallel-uglify-plugin? If yes, i am willing to send a PR.

**Comment by Xuffy** [comment]
Has the problem been solved?

**Comment by wxy1995** [comment]
I just write a simple webpack plugin to ignore these warnings:

IgnoreCssOrderConflictPlugin.js:
```
module.exports = class IgnoreCssOrderConflictPlugin {
    apply(compiler) {
        const messageRegExp = /chunk \w+ \[mini-css-extract-plugin[^]*Conflicting order between:/
        function doneHook(stats) {
            stats.compilation.warnings = stats.compilation.warnings.filter(function(warn) {
                if (messageRegExp.test(warn.message)) {
                    return false
                }
                return true;
            })
        }
        if (compiler.hooks) {
            compiler.hooks.done.tap("IgnoreCssOrderConflictPlugin", doneHook)
        } else {
            compiler.plugin("done", doneHook)
        }
    }
}
```

webpack.config.js
```
plugins: [
    ...,
    new IgnoreCssOrderConflictPlugin(),
    ...
]
```

**Comment by LofhJann** [comment]
This should be fixed before Webpack 5 (in Alpha now, no release date set yet) since all items deprecated with Webpack 4 will be removed in that release (as mentioned in https://github.com/webpack/changelog-v5/blob/master/README.md)

**Comment by gdborton** [comment]
This has been updated for the `2.0.0` release.
