### ISSUE TITLE
can't uglify @antv/g6

### ISSUE THREAD

**Issue by rawKylin** [gdborton/webpack-parallel-uglify-plugin#62]
Hi bro,
    I have used this plugin successful to build until my porject quote @antv/g6. I don't  know how to fix it. can you help me?

**Comment by rawKylin** [comment]
> Hi bro,
> I have used this plugin successful to build until my porject quote @antv/g6. I don't know how to fix it. can you help me? webpack vesion is 4.28.4

**Comment by gdborton** [comment]
@rawKylin Apologies, this package hasn't seen the love that it deserves.  The most common issue when using this package is usually when trying to use uglifyJS to minify es6 code. I would need to see the error you're getting to know for sure what's wrong.

Given the age of this issue, I'm going to hope that you were able to resolve this on your own. If not, feel free to reopen and I'll help get you sorted.
