### ISSUE TITLE
when I use it ,my project throw "maximum call stack size exceeded"

### ISSUE THREAD

**Issue by NEVERGIVEUP0922** [gdborton/webpack-parallel-uglify-plugin#64]
when I use it ,my project throw "maximum call stack size exceeded";However, if I use  webpack.optimize.UglifyJsPlugin ,it`s ok. But why?

**Comment by gdborton** [comment]
@NEVERGIVEUP0922 any chance you can help me out with a simple reproduction? Could be your actual project or a sample one. Airbnb has been using this package for several years without issue for very large projects.

**Comment by xiafengaha** [comment]
If the webpack version of your project is 3. X, it is recommended that you use version 1.1.0, otherwise the latest version will report this error

**Comment by gdborton** [comment]
If this was specific to a webpack version, I'm going to assume this has been fixed in the `2.0.0` release as I've updated the api to match webpack 5.
