### ISSUE TITLE
Sourcemaps are missing

### ISSUE THREAD

**Issue by AndyOGo** [gdborton/webpack-parallel-uglify-plugin#7]
In my webpack config I have enabled sourcemaps by `devtool: 'source-map'`, but they don't show in generated files.

**Comment by AndyOGo** [comment]
@gdborton 
Did you find any time to look in to this?

If anyone else is conserned about sourcemaps, there is also [`webpack-uglify-parallel`](https://www.npmjs.com/package/webpack-uglify-parallel), which does generate proper sourcemaps.

**Comment by gdborton** [comment]
@AndyOGo Source maps should be working as of 0.2.0.
