### ISSUE TITLE
Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by ankeji** [gdborton/webpack-parallel-uglify-plugin#70]
你的这个2.0.0版本有问题，1.0.0就是没有问题的，会报错Cannot read property 'tapAsync' of undefined

**Comment by qiwang97** [comment]
I get the same error

**Comment by gdborton** [comment]
2.0.0 was breaking, updated to newer versions of webpack, and dropped support for older versions. I'll update the changelog to be more descriptive.  I believe webpack-cli uses webpack v3.


changelog:
https://github.com/gdborton/webpack-parallel-uglify-plugin/blob/master/CHANGELOG.md


Will be closing this out, feel free to reopen if you think this is a mistake or if you see an issue when using w/ webpack 5.
